version: '3.7'
services:
  rsm-msba:
    image: "vnijs/radiant"
    environment:
      SHELL: /bin/bash
      PYTHONUSERBASE: /home/jovyan/.rsm-msba
    ports:
      - 127.0.0.1:8181:8181
      - 127.0.0.1:8787:8787
      - 127.0.0.1:2121:22
    volumes:
      - ~:/home/jovyan
  selenium_0:
    image: 
      selenium/standalone-firefox
    ports:
      - 127.0.0.1:4444:4444
